package com.github.ulviar.icli.core.pool.internal.worker;

import com.github.ulviar.icli.core.ExecutionOptions;
import com.github.ulviar.icli.core.InteractiveSession;
import com.github.ulviar.icli.core.pool.api.WorkerRetirementReason;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.time.Instant;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicReference;
import org.jetbrains.annotations.Nullable;

/**
 * Mutable record of a pooled worker process. The {@link com.github.ulviar.icli.core.pool.internal.state.PoolState}
 * owns each instance and mutates it only while holding the shared pool lock, allowing callers outside the package to
 * treat the type as thread-confined.
 *
 * <p>Each worker maintains:
 * <ul>
 *     <li>Identity and launch metadata ({@link #id()}, {@link #createdAt()}, {@link #options()}).</li>
 *     <li>Lease state, including the active request id, reuse counter, and last-used timestamp.</li>
 *     <li>A lazily populated retirement cause that guards against duplicate retire requests.</li>
 * </ul>
 *
 * <p>The class deliberately avoids synchronisation beyond the {@link AtomicReference} used for retirement cause. All
 * state transitions except {@link #requestRetire(WorkerRetirementReason)}, {@link #retirementCause()}, and
 * {@link #retireRequested()} must occur while holding the pool lock to keep the {@link SuppressFBWarnings} contract
 * intact. Retirement can be requested from threads outside the lock (e.g., timeout callbacks), hence the atomic
 * guard.
 */
@SuppressFBWarnings(
        value = "AT_NONATOMIC_OPERATIONS_ON_SHARED_VARIABLE",
        justification = "PoolWorker state mutates only while holding the PoolState lock; retirementCause is atomic")
public final class PoolWorker {

    private final int id;
    private final InteractiveSession session;
    private final ExecutionOptions options;
    private final Instant createdAt;
    private long reuseCount;
    private final AtomicReference<WorkerRetirementReason> retirementCause =
            new AtomicReference<>(WorkerRetirementReason.NOT_RETIRED);
    private @Nullable UUID activeRequestId;
    private Instant lastUsed;

    /**
     * Constructs a worker representation for the given process.
     *
     * @param id        stable identifier assigned by the pool
     * @param session   interactive session backing the worker
     * @param options   execution options used to launch the session
     * @param createdAt timestamp recorded by the pool clock when the worker was created
     */
    public PoolWorker(int id, InteractiveSession session, ExecutionOptions options, Instant createdAt) {
        this.id = id;
        this.session = session;
        this.options = options;
        this.createdAt = createdAt;
        this.lastUsed = createdAt;
    }

    /**
     * Returns the stable worker identifier.
     *
     * @return worker id
     */
    public int id() {
        return id;
    }

    /**
     * Returns the live interactive session backing this worker.
     *
     * @return interactive session
     */
    public InteractiveSession session() {
        return session;
    }

    /**
     * Returns the immutable execution options applied when launching the worker.
     *
     * @return launch options
     */
    public ExecutionOptions options() {
        return options;
    }

    /**
     * Number of completed requests served by this worker.
     *
     * @return reuse counter
     */
    public long reuseCount() {
        return reuseCount;
    }

    /**
     * Timestamp indicating when the worker process was created.
     *
     * @return creation timestamp
     */
    public Instant createdAt() {
        return createdAt;
    }

    /**
     * Records that the worker has been leased to a caller.
     *
     * <p>Must be invoked while holding the shared pool lock.
     *
     * @param requestId unique identifier for the lease, generated by
     *                  {@link com.github.ulviar.icli.core.pool.internal.lease.DefaultLeaseScope}
     */
    public void markLeased(UUID requestId) {
        if (activeRequestId != null) {
            throw new IllegalStateException("Worker " + id + " is already leased to " + activeRequestId);
        }
        activeRequestId = requestId;
    }

    /**
     * Records that the worker has been returned to the pool, updating reuse counters and timestamps.
     *
     * <p>Must be invoked while holding the shared pool lock. Callers may invoke the method redundantly; only the first
     * transition from leased to idle performs state updates.
     *
     * @param now timestamp captured by the pool clock at return time
     *
     * @return {@code true} if the worker transitioned from leased to idle, {@code false} when the worker was already
     * idle
     */
    public boolean markReturned(Instant now) {
        UUID currentRequest = activeRequestId;
        if (currentRequest == null) {
            return false;
        }
        reuseCount++;
        lastUsed = now;
        activeRequestId = null;
        return true;
    }

    /**
     * Indicates whether retirement has been requested.
     *
     * <p>Thread-safe without holding the pool lock.
     *
     * @return {@code true} if the worker should be retired
     */
    public boolean retireRequested() {
        return retirementCause.get() != WorkerRetirementReason.NOT_RETIRED;
    }

    /**
     * Requests worker retirement, preserving the first reason observed. Subsequent invocations are ignored so the
     * original cause remains visible to diagnostics.
     *
     * @param reason retirement reason to record
     */
    public void requestRetire(WorkerRetirementReason reason) {
        retirementCause.compareAndSet(WorkerRetirementReason.NOT_RETIRED, reason);
    }

    /**
     * Returns the most recent time the worker completed a lease or was created.
     *
     * @return last-used timestamp
     */
    public Instant lastUsed() {
        return lastUsed;
    }

    /**
     * Returns the request identifier associated with the current lease, or {@code null} when idle.
     *
     * @return active request id or {@code null}
     */
    @Nullable
    public UUID activeRequestId() {
        return activeRequestId;
    }

    /**
     * Returns the retirement reason, defaulting to {@link WorkerRetirementReason#NOT_RETIRED}.
     *
     * <p>Thread-safe without holding the pool lock.
     *
     * @return retirement reason
     */
    public WorkerRetirementReason retirementCause() {
        return retirementCause.get();
    }

    @Override
    public String toString() {
        return "PoolWorker{"
                + "id=" + id
                + ", reuseCount=" + reuseCount
                + ", lastUsed=" + lastUsed
                + ", activeRequestId=" + activeRequestId
                + ", retirementCause=" + retirementCause.get()
                + '}';
    }
}
